-- "My Stats" goes MULTI-ACCOUNT (v0.83, user directive 2026-07-29: "for
-- MyStats page, I need you to get the account based on what I'm logged in
-- with, then save it so it can be fetched from a list when needed").
--
-- WHY THIS MIGRATION IS THE LOAD-BEARING PART OF THAT FEATURE, not the
-- plumbing around it. Before this file, coachbuild.my_matches had NO account
-- column at all -- match_id was the whole primary key and every read
-- (/api/mystats/summary, /api/mystats/matchups, lib/draft/recommend.ts's
-- personal badges, the OTP priority walk) selected the entire table. Simply
-- repointing my_account at a second Riot ID would therefore have MERGED two
-- players' games into one dataset: win rate, champion pool, build adherence,
-- KDA and the Draft page's personal records would each have become two people
-- presented as one number, with no visible symptom. That is a HARD RULE 4
-- ("no fabricated data") violation of the worst kind -- silent and confident.
-- So account scoping lands in the SCHEMA first, and the reads are rewritten
-- against it in the same ship.
--
-- IDENTITY KEY = puuid, NOT riot_id. A Riot ID is renameable
-- ("MunsterHunter#EUW" today, something else after a name change) and the
-- account is the same account either way -- keying match rows on riot_id would
-- orphan an entire history behind a rename. The puuid is Riot's own stable
-- per-account identifier and never changes, so it is what my_matches and
-- my_ingest_cursor are scoped by.
--
-- See lib/mystats/account.ts for the read/write contract, and
-- HANDOFF-engy.md for the picker-UI contract this exposes.

-- ── my_account: one row per linked account, exactly one active ─────────────
--
-- The CHECK (id = 1) from migration 0012 was the single-account assumption
-- expressed as a constraint. It goes, and `active` replaces it: the feature
-- still has exactly ONE account whose data every My Stats surface shows, but
-- the table may now hold several to switch between.
ALTER TABLE coachbuild.my_account DROP CONSTRAINT IF EXISTS my_account_id_check;

-- `id` defaulted to the literal 1, so a second INSERT would have collided on
-- the primary key. An identity column starting at 2 keeps the existing row's
-- id=1 stable (it is the value lib/mystats/** and the picker contract will
-- keep referring to) while letting new accounts allocate normally.
ALTER TABLE coachbuild.my_account ALTER COLUMN id DROP DEFAULT;
ALTER TABLE coachbuild.my_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);

-- The real natural key. UNIQUE so an upsert of an already-linked account can
-- ON CONFLICT (puuid) instead of racing a SELECT-then-INSERT, and so the same
-- account can never be linked twice under two ids (which would silently split
-- one history in half -- the mirror image of the merge bug above).
ALTER TABLE coachbuild.my_account ADD CONSTRAINT my_account_puuid_key UNIQUE (puuid);

-- Which account every My Stats surface is currently showing.
ALTER TABLE coachbuild.my_account ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT false;

-- When the companion last reported this account as the one logged into the
-- League client (GET /me, companion 1.10.0). Display-only ordering hint for
-- the picker -- never a filter, and never used to auto-switch.
ALTER TABLE coachbuild.my_account ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;

-- The pre-existing row is the active account: it is MunsterHunter#EUW, whose
-- 138 match rows are the entire current contents of my_matches.
UPDATE coachbuild.my_account SET active = true WHERE id = 1;

-- "At most one active row" enforced by the DATABASE, not by application code
-- being careful. setActiveAccount (lib/mystats/account.ts) deactivates-then-
-- activates in two statements, and this index is what guarantees a bug or a
-- crash between them can never leave two accounts active -- which would make
-- getActiveAccount's single-row read non-deterministic, i.e. My Stats would
-- silently show whichever row Postgres happened to return first.
CREATE UNIQUE INDEX IF NOT EXISTS my_account_one_active_idx
  ON coachbuild.my_account ((active)) WHERE active;

-- ── my_matches: account-scoped ────────────────────────────────────────────
ALTER TABLE coachbuild.my_matches ADD COLUMN IF NOT EXISTS puuid text;

-- ATTRIBUTION OF THE EXISTING 138 ROWS. They are MunsterHunter#EUW's games --
-- established by the real Live Client Data capture in _capture/
-- live-client-report-20260727-140136.txt (riotId "MunsterHunter#EUW") and by
-- the fact that the single my_account row's puuid is the only puuid the
-- ingest has ever walked. They are attributed to that account, NOT orphaned,
-- NOT deleted, and NOT left ambiguous. The subquery reads id = 1 specifically
-- (not "the active account") so this backfill means the same thing no matter
-- what the active flag is when it runs.
UPDATE coachbuild.my_matches
  SET puuid = (SELECT puuid FROM coachbuild.my_account WHERE id = 1)
  WHERE puuid IS NULL;

-- Belt-and-braces: if my_account were somehow empty when this ran, the UPDATE
-- above would have set NULL and this would fail loudly rather than leave
-- unattributable rows behind. An un-attributed match row is exactly the
-- ambiguity this whole migration exists to prevent, so it must not be
-- representable.
ALTER TABLE coachbuild.my_matches ALTER COLUMN puuid SET NOT NULL;

-- A row identifies "THIS ACCOUNT's record of this match", so that pair is the
-- key. Keeping match_id alone as the PK would mean an insert for account B
-- silently no-op'ing under ON CONFLICT DO NOTHING against account A's row for
-- the same game -- losing a real game with no error.
ALTER TABLE coachbuild.my_matches DROP CONSTRAINT my_matches_pkey;
ALTER TABLE coachbuild.my_matches ADD CONSTRAINT my_matches_pkey PRIMARY KEY (puuid, match_id);

-- Every read index gets puuid as its LEADING column, because every read is now
-- account-scoped. The old un-prefixed indexes are dropped rather than kept:
-- leaving them would let a query that FORGOT the puuid filter still look fast
-- and healthy, which is precisely the failure this migration is guarding
-- against being easy to write.
DROP INDEX IF EXISTS coachbuild.my_matches_champ_role_opp_idx;
DROP INDEX IF EXISTS coachbuild.my_matches_game_creation_idx;
DROP INDEX IF EXISTS coachbuild.my_matches_split_idx;
CREATE INDEX IF NOT EXISTS my_matches_acct_champ_role_opp_idx
  ON coachbuild.my_matches (puuid, champion_id, role, opp_champion_id);
CREATE INDEX IF NOT EXISTS my_matches_acct_game_creation_idx
  ON coachbuild.my_matches (puuid, game_creation DESC);
CREATE INDEX IF NOT EXISTS my_matches_acct_split_idx
  ON coachbuild.my_matches (puuid, split);

-- ── my_ingest_cursor: per-account ─────────────────────────────────────────
--
-- This table is why "just repoint the account" could never have worked even
-- if the data merge were somehow acceptable. Its single id=1 row currently
-- reads backfill_done = true, so runMyStatsIngest's backfill mode would have
-- treated a BRAND NEW account's empty history as already fully walked and
-- returned a no-op -- the new account would show zero games forever, and the
-- 3-minute incremental cooldown would have been shared between accounts too.
ALTER TABLE coachbuild.my_ingest_cursor ADD COLUMN IF NOT EXISTS puuid text;

UPDATE coachbuild.my_ingest_cursor
  SET puuid = (SELECT puuid FROM coachbuild.my_account WHERE id = 1)
  WHERE puuid IS NULL;

-- Rows with no account attribution are deleted rather than kept: a cursor is
-- cheap derived state (an offset into a Riot match-history walk), so
-- discarding an unattributable one costs at most a re-walk, whereas keeping
-- it risks applying one account's offset to another's history.
DELETE FROM coachbuild.my_ingest_cursor WHERE puuid IS NULL;

ALTER TABLE coachbuild.my_ingest_cursor ALTER COLUMN puuid SET NOT NULL;

-- `id` is DROPPED, not merely supplemented. Every cursor query in
-- lib/mystats/** used WHERE id = 1 / INSERT (id, ...) ON CONFLICT (id); if the
-- column survived, any one of those left un-rewritten would keep working
-- perfectly while silently reading or clobbering another account's cursor.
-- Removing the column turns that class of mistake into a hard error at query
-- time instead of a silent cross-account write. Dropping it also drops the
-- PK and the CHECK (id = 1) that rode on it.
ALTER TABLE coachbuild.my_ingest_cursor DROP COLUMN id;
ALTER TABLE coachbuild.my_ingest_cursor ADD CONSTRAINT my_ingest_cursor_pkey PRIMARY KEY (puuid);
