// ─────────────────────────────────────────────────────────────────────────────
// counterItems.ts -- the PINNED item-id allowlists the enemy-comp signal is
// allowed to act on. Generated by scripts/derive-enemycomp-tables.mjs and
// verified against a captured catalogue by lib/__tests__/enemyComp-counterItems
// .test.ts, which fails the build when source and derivation disagree.
//
// IDS IN SOURCE, NEVER A RUNTIME REGEX. Two measured reasons (2026-08-29,
// live 16.16.1 catalogue), both of which a text classifier walks straight into:
//
//   1. /Grievous Wounds/ finds Mortal Reminder and Morellonomicon and MISSES
//      Thornmail (3075) and Chempunk Chainsword (6609). On Summoner's Rift
//      those two read "apply 40% Wounds"; only their ARENA variants (223075,
//      226609) spell out "Grievous Wounds". Half the class, with no error.
//   2. `maps["11"] === true` is not a Summoner's Rift filter. 323075
//      (Thornmail), 323222 (Mikael's) and 663172 (Zephyr) all set it and are
//      mode variants. `id < 10000` is required too.
//
// Upstream copy is not a contract. When Riot renames the keyword again the CI
// test goes red instead of the class going quietly empty.
// ─────────────────────────────────────────────────────────────────────────────

/** Boots carrying magic resist and/or tenacity. Mercury's Treads and its
 *  tier-3 enchant. This is the promotion target for BOTH the heavy-CC rule and
 *  the heavy-AP rule: Riot ships exactly one defensive boot per damage type, so
 *  the two rules converge here by construction rather than by coincidence. */
export const MAGIC_RESIST_BOOTS: ReadonlySet<number> = new Set([
  3111, // Mercury's Treads
  3173, // Chainlaced Crushers (tier-3 enchant of 3111)
]);

/** Boots carrying armour. Plated Steelcaps and its tier-3 enchant. The
 *  promotion target for the heavy-AD rule. */
export const ARMOR_BOOTS: ReadonlySet<number> = new Set([
  3047, // Plated Steelcaps
  3174, // Armored Advance (tier-3 enchant of 3047)
]);

/**
 * Anti-heal items. **Present as a NEGATIVE CONTROL and nothing else.**
 *
 * User decision 2026-08-29: anti-heal never enters the exported item set,
 * because it cannot be delivered honestly. Measured across 24 champion-roles
 * on production, an anti-heal item appears anywhere in the champion's own
 * `/api/build` data (core, boots, starter, fourthPlus, optimizedPath and every
 * alt) for only **9 of 24**, and for **0 of the 4 AP champions sampled**
 * (Viktor, Ahri, Orianna, Lux). Promoting it would mean injecting an item the
 * champion's own data never offered, under a block title that claims a source
 * -- HARD RULE 4, and the first fabricated recommendation in the app.
 *
 * So this set exists so a test can assert the signal NEVER promotes one of
 * these ids, for any comp, on any champion. Deleting it would delete the proof.
 */
export const ANTI_HEAL: ReadonlySet<number> = new Set([
  3033, // Mortal Reminder
  3075, // Thornmail
  3076, // Bramble Vest (component)
  3123, // Executioner's Calling (component)
  3165, // Morellonomicon
  3916, // Oblivion Orb (component)
  6609, // Chempunk Chainsword
]);

/** Every id this module is willing to name, for the exhaustiveness test. */
export const ALL_COUNTER_ITEM_IDS: ReadonlySet<number> = new Set([
  ...MAGIC_RESIST_BOOTS,
  ...ARMOR_BOOTS,
  ...ANTI_HEAL,
]);

export type CounterBootsClass = "magic-resist" | "armor";

/** Fail-closed: an id this module has never heard of is not a counter boot.
 *  Returning null (rather than guessing from tags at runtime) is what keeps a
 *  catalogue change loud -- see the header. */
export function counterBootsClass(itemId: number): CounterBootsClass | null {
  if (MAGIC_RESIST_BOOTS.has(itemId)) return "magic-resist";
  if (ARMOR_BOOTS.has(itemId)) return "armor";
  return null;
}

export function isAntiHeal(itemId: number): boolean {
  return ANTI_HEAL.has(itemId);
}
