// ─────────────────────────────────────────────────────────────────────────────
// counterItems.ts -- the PINNED item-id allowlists the enemy-comp signal is
// allowed to act on. Generated by scripts/derive-enemycomp-tables.mjs and
// verified against a captured catalogue by lib/__tests__/enemyComp-counterItems
// .test.ts, which fails the build when source and derivation disagree.
//
// IDS IN SOURCE, NEVER A RUNTIME REGEX. Two measured reasons (2026-08-29,
// live 16.16.1 catalogue), both of which a text classifier walks straight into:
//
//   1. /Grievous Wounds/ finds Mortal Reminder and Morellonomicon and MISSES
//      Thornmail (3075) and Chempunk Chainsword (6609). On Summoner's Rift
//      those two read "apply 40% Wounds"; only their ARENA variants (223075,
//      226609) spell out "Grievous Wounds". Half the class, with no error.
//   2. `maps["11"] === true` is not a Summoner's Rift filter. 323075
//      (Thornmail), 323222 (Mikael's) and 663172 (Zephyr) all set it and are
//      mode variants. `id < 10000` is required too.
//
// Upstream copy is not a contract. When Riot renames the keyword again the CI
// test goes red instead of the class going quietly empty.
// ─────────────────────────────────────────────────────────────────────────────

/** Boots carrying magic resist and/or tenacity. Mercury's Treads and its
 *  tier-3 enchant. This is the promotion target for BOTH the heavy-CC rule and
 *  the heavy-AP rule: Riot ships exactly one defensive boot per damage type, so
 *  the two rules converge here by construction rather than by coincidence. */
export const MAGIC_RESIST_BOOTS: ReadonlySet<number> = new Set([
  3111, // Mercury's Treads
  3173, // Chainlaced Crushers (tier-3 enchant of 3111)
]);

/** The tier-2 magic-resist boot by name, for lib/enemyComp/scenarioItems.ts.
 *
 *  A NAMED CONSTANT RATHER THAN A LITERAL 3111, and it is asserted to be a
 *  MEMBER of the derived set above by the same CI test that pins the set. So
 *  the scenario table's boots answer is still guarded by the catalogue
 *  derivation even though it names one id rather than a class -- which it has
 *  to, because a build line holds one pair of boots and a set is not an answer
 *  to "which boot". The tier-3 enchant is deliberately NOT the answer: it is a
 *  later upgrade of whichever boot you took, not a different reading of the
 *  comp. */
export const MERCURYS_TREADS = 3111;

/** Boots carrying armour. Plated Steelcaps and its tier-3 enchant. The
 *  promotion target for the heavy-AD rule. */
export const ARMOR_BOOTS: ReadonlySet<number> = new Set([
  3047, // Plated Steelcaps
  3174, // Armored Advance (tier-3 enchant of 3047)
]);

/** The tier-2 armour boot by name. Same contract as MERCURYS_TREADS. */
export const PLATED_STEELCAPS = 3047;

/**
 * Anti-heal items. TWO duties, and they pull in opposite directions on
 * purpose.
 *
 * 1. **NEGATIVE CONTROL for the SITUATIONAL row.** User decision 2026-08-29:
 *    anti-heal never enters that row, because there it cannot be delivered
 *    honestly. The situational contract is that a promoted item must already
 *    exist in the champion's own measured pool, and it does not. Measured
 *    across 24 champion-roles
 * on production, an anti-heal item appears anywhere in the champion's own
 * `/api/build` data (core, boots, starter, fourthPlus, optimizedPath and every
 * alt) for only **9 of 24**, and for **0 of the 4 AP champions sampled**
 * (Viktor, Ahri, Orianna, Lux). Promoting it would mean injecting an item the
 * champion's own data never offered, under a block title that claims a source
 * -- HARD RULE 4, and the first fabricated recommendation in the app.
 *
 *    So a test asserts nothing on that path ever promotes one of these ids,
 *    for any comp, on any champion. Deleting the set would delete the proof.
 *
 * 2. **MEMBERSHIP ORACLE for the "For this game" block.** That block is
 *    explicitly a JUDGMENT build rather than a claim about the champion's own
 *    data, so the honesty argument above does not apply to it and the user
 *    directive of 2026-08-29 names Morellonomicon as its headline case. Every
 *    anti-heal id lib/enemyComp/scenarioItems.ts names must be a member of this
 *    set, which is DERIVED from the catalogue's own description text -- so a
 *    Riot keyword rename fails the build instead of silently recommending an
 *    item that no longer does the thing it was chosen for.
 *
 * The two duties are not in tension: one says "never on that surface", the
 * other says "only ids the catalogue still agrees are anti-heal". Both are
 * checked by tests that name each other.
 */
export const ANTI_HEAL: ReadonlySet<number> = new Set([
  3033, // Mortal Reminder
  3075, // Thornmail
  3076, // Bramble Vest (component)
  3123, // Executioner's Calling (component)
  3165, // Morellonomicon
  3916, // Oblivion Orb (component)
  6609, // Chempunk Chainsword
]);

/** Every id this module is willing to name, for the exhaustiveness test. */
export const ALL_COUNTER_ITEM_IDS: ReadonlySet<number> = new Set([
  ...MAGIC_RESIST_BOOTS,
  ...ARMOR_BOOTS,
  ...ANTI_HEAL,
]);

export type CounterBootsClass = "magic-resist" | "armor";

/** Fail-closed: an id this module has never heard of is not a counter boot.
 *  Returning null (rather than guessing from tags at runtime) is what keeps a
 *  catalogue change loud -- see the header. */
export function counterBootsClass(itemId: number): CounterBootsClass | null {
  if (MAGIC_RESIST_BOOTS.has(itemId)) return "magic-resist";
  if (ARMOR_BOOTS.has(itemId)) return "armor";
  return null;
}

export function isAntiHeal(itemId: number): boolean {
  return ANTI_HEAL.has(itemId);
}
